plugins:
  mediabot_enabled:
    default: false
    client: true
  mediabot_tmdb_api_key:
    default: ""
    secret: true
  mediabot_tvdb_api_key:
    default: ""
    secret: true
  mediabot_enabled_tags:
    default: "movie,tv"
    client: true
  mediabot_enabled_categories:
    default: ""
    client: true
  mediabot_enable_inline_commands:
    default: true
    client: true
  mediabot_show_title:
    default: true
    client: true
  mediabot_show_poster:
    default: true
    client: true
  mediabot_show_overview:
    default: true
    client: true
  mediabot_show_cast:
    default: true
    client: true
  mediabot_show_rating:
    default: true
    client: true
  mediabot_show_genres:
    default: true
    client: true
  mediabot_show_runtime:
    default: true
    client: true
  mediabot_show_external_links:
    default: true
    client: true
  mediabot_reply_delay:
    default: 0
    client: true

# Display Options
mediabot_show_release_date:
  default: true
  client: true

# Behavior Settings
mediabot_use_user_locale:
  default: true
  client: true
mediabot_fallback_locale:
  default: "en-US"
  client: true
mediabot_supported_locales:
  default: "en-US,es-ES,fr-FR,de-DE,it-IT,pt-BR,ru-RU,ja-JP,ko-KR,zh-CN"
  client: true